### ISSUE TITLE
net structure

### ISSUE THREAD

**Issue by 1alebra2** [ANTsX/ANTsRNet#6]
Hello
I was trying to run the brainextraction exsample and the trained net does not load. The number of layers of the net in the r code and the trained net seem not to fit, after some searching it gives a message that the r net has 15 layers, and the trained net 18. Could someone probably help with that. I am aware that the main work is training the net, so I would appreciate any help

**Comment by ntustison** [comment]
Thanks for pointing this out.  It should be fixed now with the latest ANTsRNet repository.  I had made some changes associated with our python analog (ANTsPyNet) and introduced a bug which I just fixed.

**Comment by 1alebra2** [comment]
Dear Nick 
Thanks lot. I will give it a new try
Alexander’s 

> Am 19.06.2019 um 17:39 schrieb Nick Tustison <notifications@github.com>:
> 
> Thanks for pointing this out. It should be fixed now with the latest ANTsRNet
repository. I had made some changes associated with our python analog
(ANTsPyNet) and introduced a bug which I just fixed.

**Comment by 1alebra2** [comment]
Hi Nick,

All examples work, except the WholeTumorSegmentation. Here I still get this funny error, either "wrong signature" or differing numbers of layers between the net and the weights.
Would you mind checking again?  Thank you

Another question: Using  MatchhistogramMatchImage.R I get an error by antscloneimage about " missing slots" obviously a S4 object problem. I am reading the images with readNIFTI

any idea

Thank you 

A

**Comment by ntustison** [comment]
I just ran it using the latest pull from ANTsRNet and it worked fine (see below).  

Regarding your second question---``readNIFTI`` reads in the nifti image into a completely separate data object as an antsImage.  There's no cross-compatibility.

```
$ Rscript Scripts/doWholeTumorSegmentation.R Data/Example/brats_tcia_pat222_2/T2.nii.gz Data/Example/brats_tcia_pat222_2/Flair.nii.gz Data/Example/brats_tcia_pat222_2/BrainExtractionMask.nii.gz output Data/Template/S_template3_resampled2.nii.gz 

*** Successfully loaded .Rprofile ***

Loading required package: ANTsRCore

Attaching package: ‘ANTsRCore’

The following object is masked from ‘package:stats’:

    var

The following objects are masked from ‘package:base’:

    all, any, apply, max, min, prod, range, sum

Reading reorientation template Data/Template/S_template3_resampled2.nii.gz  (elapsed time: 0.2036459 seconds)
Using TensorFlow backend.
WARNING:tensorflow:From /Users/ntustison/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Loading weights file2019-07-30 06:45:10.653908: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
  (elapsed time: 0.5730999 seconds)
Reading input.  (elapsed time: 0.657131 seconds)
Normalizing to template and cropping to mask.  (elapsed time: 1.60081 seconds)
Prediction and decoding (elapsed time: 26.28147 seconds)
Renormalize to native space  (elapsed time: 0.7662148 seconds)
Writing output  (elapsed time: 1.656777 seconds)

Total elapsed time: 30.96547 seconds
```

**Comment by 1alebra2** [comment]
Thanks a lot
So i have to check and find out


> Am 30.07.2019 um 15:49 schrieb Nick Tustison <notifications@github.com>:
> 
> I just ran it using the latest pull from ANTsRNet and it worked fine (see
below).
> 
> Regarding your second question---readNIFTI reads in the nifti image into a
completely separate data object as an antsImage. There's no
cross-compatibility.
> 
> $ Rscript Scripts/doWholeTumorSegmentation.R
Data/Example/brats_tcia_pat222_2/T2.nii.gz
Data/Example/brats_tcia_pat222_2/Flair.nii.gz
Data/Example/brats_tcia_pat222_2/BrainExtractionMask.nii.gz output
Data/Template/S_template3_resampled2.nii.gz 
> 
> 
> 
> *** Successfully loaded .Rprofile ***
> 
> 
> 
> Loading required package: ANTsRCore
> 
> 
> 
> Attaching package: ‘ANTsRCore’
> 
> 
> 
> The following object is masked from ‘package:stats’:
> 
> 
> 
>     var
> 
> 
> 
> The following objects are masked from ‘package:base’:
> 
> 
> 
>     all, any, apply, max, min, prod, range, sum
> 
> 
> 
> Reading reorientation template Data/Template/S_template3_resampled2.nii.gz 
(elapsed time: 0.2036459 seconds)
> 
> Using TensorFlow backend.
> 
> WARNING:tensorflow:From
/Users/ntustison/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263:
colocate_with (from tensorflow.python.framework.ops) is deprecated and will be
removed in a future version.
> 
> Instructions for updating:
> 
> Colocations handled automatically by placer.
> 
> Loading weights file2019-07-30 06:45:10.653908: I
tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports
instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 
>   (elapsed time: 0.5730999 seconds)
> 
> Reading input.  (elapsed time: 0.657131 seconds)
> 
> Normalizing to template and cropping to mask.  (elapsed time: 1.60081
seconds)
